export const TEAM_TO_ISO = {
  'Belgija': 'BE',
  'Bosnija ir Hercegovina': 'BA',
  'Kipras': 'CY',
  'Čekija': 'CZ',
  'Estija': 'EE',
  'Suomija': 'FI',
  'Prancūzija': 'FR',
  'Sakartvelas': 'GE',
  'Vokietija': 'DE',
  'Didžioji Britanija': 'GB',
  'Graikija': 'GR',
  'Islandija': 'IS',
  'Izraelis': 'IL',
  'Italija': 'IT',
  'Latvija': 'LV',
  'Lietuva': 'LT',
  'Juodkalnija': 'ME',
  'Lenkija': 'PL',
  'Portugalija': 'PT',
  'Serbija': 'RS',
  'Slovėnija': 'SI',
  'Ispanija': 'ES',
  'Švedija': 'SE',
  'Turkija': 'TR',
};