name: Deploy Vite site to Hostinger (prod)

on:
  push:
    branches: [ "prod" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build project
        working-directory: client
        run: npm run build

      - name: Deploy dist/ via rsync over SSH
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: client/dist/   # <- new location
          remote_path: /home/u775869936/domains/icrib.pro/public_html/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_key: ${{ secrets.SSH_KEY }}